### ISSUE TITLE
"How to use it" not working

### ISSUE THREAD

**Issue by Raphango** [sgubianpm/pygensa#1]
Hi! I've installed your module using the available "setup.py" but when I try to run the "How to use it" example it returns me the following error:

```
C:\ProgramData\Miniconda3\python.exe C:/Users/angel/Dropbox/PYTHON/Optimization/hygsa_tests.py
Traceback (most recent call last):
  File "C:/Users/angel/Dropbox/PYTHON/Optimization/hygsa_tests.py", line 9, in <module>
    ret = hygsa(func, None, bounds=(zip(lw, up)))
  File "C:\ProgramData\Miniconda3\lib\site-packages\hygsa-0.0.3-py3.6.egg\hygsa\_hygsa.py", line 528, in hygsa
    maxfun=maxfun, maxsteps=maxiter,pure_sa=pure_sa)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hygsa-0.0.3-py3.6.egg\hygsa\_hygsa.py", line 323, in __init__
    self.owf = ObjectiveFunWrapper(bounds, fun, **minimizer_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\hygsa-0.0.3-py3.6.egg\hygsa\_hygsa.py", line 253, in __init__
    self.lower = np.array(lu[0])
IndexError: list index out of range

Process finished with exit code 1

```

Any clue on how to solve it?

**Comment by sgubianpm** [comment]
Dear @Raphango ,
Sorry about this, I have updated the code recently and I may have broken something. I'll take a look today and get back to you.
Now fixed. Still old way bounds initialization in the example.

Best regards,

Sylvain.

**Comment by Raphango** [comment]
It works now! Thanks! =)
